spring:
  application:
    name: discodeit

  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_batch_fetch_size: 500
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false

  
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql

discodeit:
  repository:
    type: file   # jcf | file
    file-directory: .discodeit
  storage:
    type: local
    local:
      root-path: ./storage/binary-contents


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api
    operations-sorter: method
  paths-to-match: /api/**

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


